version: "3.8"

services:
  roach1:
    image: cockroachdb/cockroach:v23.2.1
    container_name: roach1
    hostname: roach1
    networks:
      - roachnet
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - roach1:/cockroach/cockroach-data
    command: start --advertise-addr=roach1:26357 --http-addr=roach1:8080 --listen-addr=roach1:26357 --sql-addr=roach1:26257 --insecure --join=roach1:26357,roach2:26358,roach3:26359

  roach2:
    image: cockroachdb/cockroach:v23.2.1
    container_name: roach2
    hostname: roach2
    networks:
      - roachnet
    ports:
      - "26258:26258"
      - "8081:8081"
    volumes:
      - roach2:/cockroach/cockroach-data
    command: start --advertise-addr=roach2:26358 --http-addr=roach2:8081 --listen-addr=roach2:26358 --sql-addr=roach2:26258 --insecure --join=roach1:26357,roach2:26358,roach3:26359

  roach3:
    image: cockroachdb/cockroach:v23.2.1
    container_name: roach3
    hostname: roach3
    networks:
      - roachnet
    ports:
      - "26259:26259"
      - "8082:8082"
    volumes:
      - roach3:/cockroach/cockroach-data
    command: start --advertise-addr=roach3:26359 --http-addr=roach3:8082 --listen-addr=roach3:26359 --sql-addr=roach3:26259 --insecure --join=roach1:26357,roach2:26358,roach3:26359

networks:
  roachnet:

volumes:
  roach1:
  roach2:
  roach3:
